name 'spikeheap-rsnapshot'
version '1.0.0'
source 'git://github.com/spikeheap/puppet_rsnapshot.git'
author 'Ryan Brooks'
description 'Resource types for managing an Rsnapshot server and remote/local clients'
summary 'Resource types for managing an Rsnapshot server and remote/local clients'
license 'GPL v3'
project_page 'https://github.com/spikeheap/puppet_rsnapshot'
## Add dependencies, if any:
dependency 'saz/ssh'